# Generated by Django 2.2.10 on 2020-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='routes_str',
            field=models.CharField(default='', max_length=200, verbose_name='Routes list'),
            preserve_default=False,
        ),
    ]
