# Generated by Django 2.2.10 on 2020-07-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_station_routes_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='routes_str',
            new_name='route_numbers',
        ),
    ]
